### ISSUE TITLE
Unable to add in home app

### ISSUE THREAD

**Issue by Crox77** [neilpatel121/homebridge-skyq-tvremote#25]
**Describe Your Problem:**
Hi Just installed Plugin however the Sky box is not found when searching in the Home app, I have also noticed in my logs its says IP address not set at device this is not true though as I have added a static IP at the device and added it into my router settings. Any ideas Please? 

**Logs:**

```
[5/28/2021, 11:44:23 AM] [Sky Q TV Remote] Initializing skyq-tvremote platform...
[5/28/2021, 11:44:23 AM] [Sky Q TV Remote] IP address not set at device 1.
[5/28/2021, 11:44:23 AM] [Sky Q TV Remote] Sky TV platform finished initializing!
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by Crox77** [comment]
ok so I have fixed the ip issue, didn't realise it meant in the setting in the UI however now when starting HB I get this error message
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Crox77** [comment]
by the way I don't have 100 devices

**Comment by andypburke** [comment]
I have the same error on 100 devices which I think is related to the number of channels as I don't get a complete list only a partial list.

**Comment by Crox77** [comment]
> I have the same error on 100 devices which I think is related to the number of channels as I don't get a complete list only a partial list.

Have you fixed it Andy? Can you explain what you mean by number of channels as I don’t understand? Thanks

**Comment by andypburke** [comment]
@Crox77 not fixed no and I have raised a separate issue in case it isn't linked.   When I add the accessory the plugin finds a number of Sky Q channels.  I subscribe to the full set so have over 250 channels including Sports and Movies.   These don't appear in the list of channels, so I am assuming it is cut off when a limit is reached. It currently stops at ITV4 +1. I am unable to modify the channel numbers neither.

**Comment by Crox77** [comment]
> @Crox77 not fixed no and I have raised a separate issue in case it isn't linked. When I add the accessory the plugin finds a number of Sky Q channels. I subscribe to the full set so have over 250 channels including Sports and Movies. These don't appear in the list of channels, so I am assuming it is cut off when a limit is reached. It currently stops at ITV4 +1. I am unable to modify the channel numbers neither.

I’ve not got as far as to have Homebridge running to find any channels so I can imagine it’s that with me, only way I can restart HB is to remove the Plugin details from my config

**Comment by andypburke** [comment]
> > @Crox77 not fixed no and I have raised a separate issue in case it isn't linked. When I add the accessory the plugin finds a number of Sky Q channels. I subscribe to the full set so have over 250 channels including Sports and Movies. These don't appear in the list of channels, so I am assuming it is cut off when a limit is reached. It currently stops at ITV4 +1. I am unable to modify the channel numbers neither.
> 
> I’ve not got as far as to have Homebridge running to find any channels so I can imagine it’s that with me, only way I can restart HB is to remove the Plugin details from my config

Ah I see.  No I can get the plugin working without any problem.

**Comment by EpicKris** [comment]
Could you test `v1.3.0-beta.1`?
